### ISSUE TITLE
error when getting user data

### ISSUE THREAD

**Issue by red78massive1573** [Kzapas/Krunker-API#1]
when i added a username to the link, it responded with an error page

**Comment by kiprasvitas** [comment]
Heroku responds with an H12 error when it takes my script more than 30 seconds to respond. Since this is kind of outdated, I doubt it will work anymore. I'm afraid I don't have time to work on this anymore so it's kind of a dead project. You are welcome to modify the project yourself. It should be an easy fix. Cheers!

**Comment by red78massive1573** [comment]
ok, thx for responding. since im new to coding, i wont be fixing any codes people made. cause, if I edit it. it could be broken xD. thanks!
